version: '3'

services:
  app:
    hostname: chroma-service
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    environment:
      PORT: 80
    volumes:
      - .:/app
      - ../cords-data/chroma:/data
    user: "1000:1000"
    working_dir: /app
    command: ./tools/init
    restart: always
