#!/bin/bash

BASE_PATH=$PWD

python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

cd $BASE_PATH/lib/chroma && pip install -e .

cd $BASE_PATH/src

gunicorn main:app \
  --timeout 360 \
  --workers 4 \
  --worker-class \
  uvicorn.workers.UvicornWorker \
  --bind 0.0.0.0:$PORT
  
