name: Deploy Stage

on:
  push:
    branches:
      - release/stage

jobs:
  deploy:
    runs-on: internal-stage

    env:
      DATA_SERVICE_URL: https://api-dev.cords.dev
      DATA_SERVICE_API_KEY: ${{ secrets.DATA_SERVICE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: ./tools/deploy /home/ubuntu/sites/chroma-service
